# Generated by Django 5.0.2 on 2024-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_category_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
