# Generated by Django 5.0.2 on 2024-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
